name: release

on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm
        run: npm ci
      - name: lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm
        run: npm ci
      - name: test
        run: npm run test

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create new branch
        run: git checkout -b releases/${{ github.run_number }}
