name: release

on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm
        run: npm ci
      - name: lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm
        run: npm ci
      - name: test
        run: npm run test

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create new branch
        run: |
          git checkout -b releases/${{ github.run_number }}
          git push origin releases/${{ github.run_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login
        run: docker login --username oauth --password ${{ secrets.YANDEX_CLOUD_TOKEN }} cr.yandex
      - name: build image
        run: docker build -t cr.yandex/crpjke8raekf9lld1bh2/app:${{ github.run_number }} -t cr.yandex/crpjke8raekf9lld1bh2/app:${{ github.run_number }}_latest .

      - name: add image to registry
        run: docker push cr.yandex/crpjke8raekf9lld1bh2/app:${{ github.run_number }}

  create_tag:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set committer identity
        run: |
          git config --global user.email "${{ secrets.GIT_COMMITTER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_COMMITTER_NAME }}"
      - name: create new branch
        run: |
          git tag -m ${{ github.run_number }} latest_commit
          git push origin --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
